# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble

  Test:
    needs: Compile

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports
        
  Assemble:
    needs: Test
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.getVer.outputs.version }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble to .jar with Gradle
      run: ./gradlew jar
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs/Lab 4-*.jar
    - name: Output Version
      id: getVer
      run: echo "::set-output name=version::$(./gradlew properties -q | grep '^version:' | awk '{print $2}')"
    
  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: Assemble
    runs-on: ubuntu-latest

    steps:
        - uses: actions/download-artifact@v2
          name: buildJar
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: buildJar/st_nycu_lab4-${{needs.Assemble.outputs.version}}.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
